image: python:3.8

stages:
  - test
  - build
  - deploy

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - /.composer-cache/

unittest:
  stage: test
  script:
    - pip install poetry
    - poetry install
    - python -m unittest -v comlipy.tests.suite

build:
  stage: build
  dependencies:
    - unittest
  before_script:
    - pip install poetry
  script:
    - poetry build
  artifacts:
    paths:
      - dist/
    expire_in: 1 days
    when: always
  only:
    refs:
      - /^v[0-9]+(?:.[0-9]+)+(?:[-]rc[0-9]+)$/
      - /^v[0-9]+(?:.[0-9]+)+$/

.deploy:
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install --upgrade twine
    - echo "$PYPIRC" > ~/.pypirc
    - chmod 600 ~/.pypirc

deploy:staging:
  extends: .deploy
  script:
    - twine upload --repository comlipy-test dist/*
  only:
    refs:
      - /^v[0-9]+(?:.[0-9]+)+(?:[-]rc[0-9]+)$/

deploy:production:
  extends: .deploy
  script:
    - twine upload --repository comlipy dist/*
  only:
    refs:
      - /^v[0-9]+(?:.[0-9]+)+$/