global:
  help: 'Help: https://gitlab.com/slashplus-build/comlipy'
rules:
  body-case:
    applicable: 'always'
    value:
    level: 0
  body-empty:
    applicable: 'never'
    value:
    level: 0
  body-leading-blank:
    applicable: 'always'
    value:
    level: 1
  body-max-length:
    applicable: 'always'
    value: Infinity
    level: 0
  body-max-line-length:
    applicable: 'always'
    value: Infinity
    level: 0
  body-min-length:
    applicable: 'always'
    value: 0
    level: 0
  footer-empty:
    applicable: 'never'
    value:
    level: 0
  footer-leading-blank:
    applicable: 'always'
    value:
    level: 1
  footer-max-length:
    applicable: 'always'
    value: Infinity
    level: 0
  footer-max-line-length:
    applicable: 'always'
    value: Infinity
    level: 0
  footer-min-length:
    applicable: 'always'
    value: 0
    level: 0
  header-case:
    applicable: 'always'
    value: 'lowerCase'
    level: 0
  header-full-stop:
    applicable: 'always'
    value: '.'
    level: 0
  header-max-length:
    applicable: 'always'
    value: 72
    level: 2
  header-min-length:
    applicable: 'always'
    value: 0
    level: 0
#  references-empty:
#    applicable: 'always'
#    value:
#    level: 0
  scope-case:
    applicable: 'always'
    value: 'lower-case'
    level: 2
  scope-empty:
    applicable: 'never'
    value:
    level: 1
  scope-enum:
    applicable: 'always'
    value: []
    level: 0
  scope-max-length:
    applicable: 'always'
    value: Infinity
    level: 0
  scope-min-length:
    applicable: 'always'
    value: 0
    level: 0
#  signed-off-by:
#    applicable: 'always'
#    value:
#    level: 0
  subject-case:
    applicable: 'always'
    value:
      - 'lower-case'
    level: 2
  subject-empty:
    applicable: 'never'
    value:
    level: 2
  subject-full-stop:
    applicable: 'never'
    value: '.'
    level: 2
  subject-max-length:
    applicable: 'always'
    value: Infinity
    level: 0
  subject-min-length:
    applicable: 'always'
    value: 0
    level: 0
  type-case:
    applicable: 'always'
    value: 'lower-case'
    level: 2
  type-empty:
    applicable: 'never'
    value:
    level: 2
  type-enum:
    applicable: 'always'
    value:
      - 'build'
      - 'chore'
      - 'ci'
      - 'docs'
      - 'feat'
      - 'fix'
      - 'improvement'
      - 'perf'
      - 'refactor'
      - 'revert'
      - 'style'
      - 'test'
    level: 2
  type-max-length:
    applicable: 'always'
    value: Infinity
    level: 0
  type-min-length:
    applicable: 'always'
    value: 0
    level: 0
ignores:
    - '^((Merge pull request)|(Merge (.*?) into (.*?)|(Merge branch (.*?)))(?:\r?\n)*$)'
    - '^(R|r)evert .*'
    - '^(fixup|squash)!'
    - '^Merged .*?(in|into) .*'
    - '^Merge remote-tracking branch .*'
    - '^Automatic merge.*'
    - '^Auto-merged .*? into .*'